### ISSUE TITLE
Η EventReception ζητάει web developer

### ISSUE THREAD

**Issue by dpapan** [thessrb/meetup#47]
Η εταιρία [ΕventReception] (http://eventreception.com) ψάχνει για έμπειρο/η web developer για μόνιμη, full-time απασχόληση, με προοπτική και για remote work.

Παρακάτω θα βρείτε το προφίλ του υποψηφίου developer που ζητάνε. Όποιος/α ενδιαφέρεται μπορεί να επικοινωνήσει απ' ευθείας με τον Σάκη Φιδάνη στο info@eventreception.com για περισσότερες πληροφορίες. Στην επικοινωνία μαζί τους απλά αναφέρετε ότι βρήκατε την αγγελία μέσω του ruby group.

-----
**Προφίλ Υποψηφίου:**
    - Απόφοιτος/η Πληροφορικής ή συναφών κλάδων.
    - Απαραίτητη προϋπηρεσία 3 ετών στην ανάπτυξη web εφαρμογών.
    - Αποδεδειγμένη συμμετοχή σε projects από την αρχική ανάπτυξη έως την τελική υλοποίηση (να αναφερθούν συγκεκριμένα παραδείγματα)
    - Να μπορεί να συνεργάζεται με τα τμήματα μάρκετινγκ και πωλήσεων ώστε να σχεδιάζει και να υλοποιεί προϊόντα ικανοποιώντας όλες τις απαιτήσεις.
 
**Απαραίτητα Προσόντα:**
    - Πολύ καλή γνώση PHP, Javascript, jQuery framework, MySQL.
    - Πολύ καλή γνώση σχεδιασμού βάσεων δεδομένων.
    - Πολύ καλή γνώση σύγχρονων διαδικτυακών τεχνολογιών (HTML/HTML5, CSS/CSS3, Αjax κλπ).
 
**Προαιρετικά:**
    - Kαλή γνώση συστημάτων διαχείρισης περιεχομένου, ηλεκτρονικού εμπορίου και Facebook API.
    - Εμπειρία στην ανάπτυξη εφαρμογών για έξυπνες συσκευές (tablets, smart phones).

**Comment by petros** [comment]
Ξέρουμε αν ισχύει ακόμα η αγγελία;
