### ISSUE TITLE
Senior Rails Developer AND front end developer wanted by Incrediblue

### ISSUE THREAD

**Issue by xarisd** [thessrb/meetup#48]
Η [Incrediblue](http://www.incrediblue.com) ζητάει Rails Developer!
wow! Ruby Job at Greece!

Επίσης ζητάει front end developer!

Για όποιον δεν ξέρει τι κάνει η Incrediblue να μια περιγραφή από το ίδιο τους το site
> incrediblue is the first online community marketplace for boat rentals, connecting travelers with trusted boat owners in several countries across the world. Featuring a growing community of users and a wide range of boats, including sailing boats and motor yacht charters, incrediblue offers worry-free, unique vacation experiences to match any budget and need.

Από έγκυρες πηγές :-) έχω μάθει ότι η εταιρία είναι ραγδέως ανερχόμενη **σε παγκόσμιο επίπεδο**, τα [παιδιά](https://twitter.com/teoulas) [που την](https://twitter.com/gatosg) [τρέχουν](https://twitter.com/afiorakis) είναι φοβερά, η [ομάδα](http://www.incrediblue.com/en/pages/team) πολύ δυνατή και το εργασιακό περιβάλλον...από άλλη ήπειρο! 

**...και γράφουν και σε Ruby**!

Τι άλλο θέλετε; Δωρεάν μαθήματα ιστιοπλοϊας; Το προσφέρουν και αυτό!

Ενδιαφέρεσαι; Μην διστάσεις! Κάνε apply for the job τώρα!

Περισσότερες πληροφορίες στα παρακάτω links:
* [Rails Developer](https://incrediblue.workable.com/jobs/24459)
* [Front End Developer](https://incrediblue.workable.com/jobs/23850)
* [All positions including marketing](https://incrediblue.workable.com)

Αν είσαι senior backend developer σε άλλη (booooo!) τεχνολογία μην διστάσεις ούτε εσύ!
Όπως αναφέρεται και μέσα στην ίδια την αγγελία:
> If you are a passionate back-end developer who believes in our mission and have extensive experience in Ruby, Rails and SQL databases, then you are the person we are looking for! We invest heavily in training junior developers and re-training experienced ones in the technologies we use. If you are experienced in other server-side frameworks and languages and eager to learn something new, we’ll be happy to consider your application as well.

**Comment by petros** [comment]
Is this still a thing?

**Comment by Drakevr** [comment]
nope confirmed to not be a thing anymore.
