### ISSUE TITLE
Chat κανάλι μέσω του gitter.im?

### ISSUE THREAD

**Issue by varemenos** [thessrb/meetup#50]
Μήπως να φτιάχναμε ένα (live) chat κανάλι μέσω του [gitter.im](http://gitter.im)?

Είδα να  το χρησιμοποιούν σε 1-2 πρότζεκτ που κάνω crawl και φάνηκε πολύ ωραίο και εύχρηστο.
ps: Προφανώς αυτό δεν θα αντικαταστήσει τα github issues

**Comment by petros** [comment]
Τελικά καταλήξαμε στο slack για την ώρα.
