### ISSUE TITLE
Next presentation proposal - Capistrano & Chef

### ISSUE THREAD

**Issue by theodorosploumis** [thessrb/meetup#53]
Me (and friends @modkaffes @sirodoht and many more...) would really like to see presentations about *Capistrano* (capistranorb.com) and *Chef* (https://rubygems.org/gems/chef) setup and recipes. They are great ruby gems and they are used widely!

Thanks.

**Comment by petros** [comment]
Νομίζω έγινε τον Φλεβάρη.
