### ISSUE TITLE
Meetup 33 prizes

### ISSUE THREAD

**Issue by petros** [thessrb/meetup#57]
Παρακάτω οι νικητές:

Δωράκι | Ποίος; | Μέγεθος
--- | ---: | :---:
t-shirt | 17 | XL
t-shirt | 2 | XL
t-shirt | 6 | M
CodeSchool | 1

Μπορείτε να μου πείτε ποιος ή ποια είναι ο 17 και ο 2, και τι μέγεθος θέλετε;

**Comment by petros** [comment]
Επιτέλους αξιώθηκα να τα παραγγείλω. Θα σας ενημερώσω προσεχώς.

**Comment by petros** [comment]
@Drakevr wrote

> για το No2 (όχι αυτόν με το ΝΟΔΕ.ΞΣ, τον real No2 που γραφει real stuff :p) το size είναι XL και θα επικοινωνήσει/έρθει λέει στο next meetup :)

Ο real No 2 παίζει να έρθει αύριο; Μπορείς να πάρεις εσύ το μπλουζάκι να του το δώσεις;

**Comment by petros** [comment]
@costasdroid αύριο θα έχω το μπλουζάκι στο meetup. Θα έρθεις;

**Comment by xarisd** [comment]
Παιδιά είχαμε ένα απρόοπτο και ο @petros δεν θα μπορέσει να έρθει σήμερα στη συνάντηση.
Συνεννοήθηκα μαζί του να πάω εγώ να πάρω τα μπλουζάκια αλλά τελικά λόγω οικογενειακών υποχρεώσεων δεν θα μπορέσω να κατέβω νωρίτερα.

Οπότε **όποιος ήταν να έρθει μόνο για να πάρει το μπλουζάκι** παρακαλώ να ξέρετε ότι δεν θα τα έχω σήμερα.

**Comment by petros** [comment]
Δωράκι | AA Κλήρωσης | Handle | Μέγεθος | Παραδόθηκε
--- | ---: | :---: | :---: | :---:
t-shirt | 17 | | XL | 
t-shirt | 2 | @costasdroid | XL | 
t-shirt | 6 | | M | 
CodeSchool | 1 | @vkamayiannis | A month | :heavy_check_mark:

**Comment by petros** [comment]
@Drakevr μπορείς να μάθεις το GitHub handle του No2;

**Comment by costasdroid** [comment]
I am. Τι ακριβώς θέλεις?

**Comment by petros** [comment]
@costasdroid ο 17 είσαι παλίκαρε. Σόρρυ. Ο 2 είναι ένας γνωστός του @Drakevr που δεν μπορώ να εντοπίσω. Επίσης λείπει και ο 6 που δεν έχω ιδέα ποιος είναι.

**Comment by Drakevr** [comment]
θα το κανονίσω, όταν ξανανεβώ.

όσο για τον 6, γιατί δεν κρατούσαμε proper index? αστο open λίγο ακόμα
και δώσε την μπλούζα σε άλλον μετά?

**Comment by petros** [comment]
Εντάξει, εντοπίστηκε ο 6 :)

Στον 2 βάζω το δικό σου handle τότε, αφού δε βρίσκουμε το handle του γνωστού σου :)

**Comment by Drakevr** [comment]
It's @DarkNikGr

**Comment by petros** [comment]
> It's @DarkNikGr

Thanks! Updated.
