### ISSUE TITLE
Adapter για την παρουσίαση του Active Record

### ISSUE THREAD

**Issue by xarisd** [thessrb/meetup#63]
@gmanolis καλημέρα! 

Επειδή ο Πέτρος δεν θα μπορέσει να έρθει σήμερα, πρέπει να συνεννοηθούμε λίγο για την παρουσίαση.

1. Θα κάνεις παρουσίαση σε ΔΙΚΟ ΣΟΥ laptop ή μπορείς να κάνεις και π.χ. στο δικό μου (mac book pro);
2. Αν κάνεις σε δικό σου laptop θα χρειαστείς αντάπτορα για τον προβολέα (ο προβολέας παίρνει VGA);

Ρωτάω τα παραπάνω για να φροντίσω τα της οργάνωσης :-)

Thanks!

**Comment by gmanolis** [comment]
@xarisd καλημέρα,
1. θα κάνω την παρουσίαση στο δικό μου, έχω στημένα διάφορα
2. έχω mac book pro με HDMI, δηλ θα χρειαστούμε adaptor, δεν έχω ...

**Comment by damphyr** [comment]
Προσοχή τα MacbookPro δεν έχουν HDMI έχουν DisplayPort :smile:

**Comment by xarisd** [comment]
Έχουν και HDMI :-) (models 2013, 2014)

**Comment by xarisd** [comment]
ΟΚ συνεννοηθήκαμε με @gmanolis. 

Θα φροντίσω να φέρω αντάπτορα...
