### ISSUE TITLE
Senior Engineers wanted by Total Eclipse

### ISSUE THREAD

**Issue by xarisd** [thessrb/meetup#64]
Guys and girls, Total Eclipse (http://www.totaleclipsegames.com/) is hiring! 

Είναι στην πόλη μας, δημιουργούν [φανταστικά παιχνίδια](https://itunes.apple.com/app/clockwork-brain-challenge/id442745768?mt=8&ign-mpt=uo%3D4) ("Over a million downloads! ", ουάου!) και πληροφορίες λένε ότι έχουν μια καταπληκτική ομάδα! 

Ψάχνουν για ταλαντούχους senior developers (backend engineer και game engineer), οπότε αν ψήνεστε, κάντε apply τώρα!

Παραθέτω το teaser:

> Total Eclipse is looking for talented Senior Engineers to bring exciting new features
> to its multi-platform games. 
> 
> Current available positions include a Senior Backend Engineer
> and a Senior Game Engineer. 
> 
> Find out more at http://totaleclipse.workable.com/

**Comment by petros** [comment]
Is this still a thing?

**Comment by dbendilas** [comment]
Yup

--
*Dimitrios Bendilas*
Co-founder / Lead Engineer
Total Eclipse
www.totaleclipsegames.com <http://www.totaleclipsegames.com>
