### ISSUE TITLE
Meetup 39: Games in Ruby & Women in tech

### ISSUE THREAD

**Issue by petros** [thessrb/meetup#69]
We are looking for guidance comments for https://git.io/thessrb-39 if have a minute to spare:

* What should we do more?
* What should we do less?
* What should we stop doing?

If you could write one sentence (or more if you want) for each questions above, that would be great!

**Comment by petros** [comment]
Υ.Γ. μπορείτε και στα Ελληνικά φυσικά :grimacing:

**Comment by petros** [comment]
Όπως επίσης οποιαδήποτε ερώτηση ή συζήτηση για τα δύο θέματα που παρουσιάσαμε μπορούν να γίνουν εδώ.

**Comment by nelaka** [comment]
Καλησπέρα! Η χθεσινή ήταν η δεύτερη φορά που ήρθα σε ruby meetup και είμαι πολύ ευχαριστημένη με αυτό που βρήκα! Συγχαρητήρια για τη δουλειά σας! Αυτό που όμως δε βρίσκω, είναι το πού ανεβάζετε τις παρουσιάσεις με τον κώδικα και τα tips του Rubyzino... Γίνετε μήπως να βάζετε κάπου το σχετικό link για να τα βρίσκουμε εύκολα και εμείς οι κοπέλες; :-p (Αυτό ήταν πλάκα, ελπίζω να μην παρεξηγηθώ! :) ) Σας ευχαριστώ και κυρίως που μας ανοίγετε λίγο τα μάτια περί ruby!

**Comment by petros** [comment]
Χαίρομαι που βρήκες τη συνάντηση χρήσιμη @nelaka. Πολύ εύστοχη η παρατήρηση για τον κώδικα και λοιπά. Παλιά ανέβαζα τις παρουσιάσεις, αλλά σταμάτησα. Πρέπει όμως να αρχίσω ξανά :smile:. Για την ώρα βάζω εδώ τα χθεσινά tips, αλλά μάλλον θα κάνω ένα rubizino section σε αυτό το repository όπου θα βάζω τα tips.

Ο κώδικας του παιχνιδιού δυστυχώς μάλλον δεν μπορώ να τον δημοσιεύσω επειδή είναι μέρος ενός commercial βιλίου, αλλά θα τσεκάρω μη τυχόν έχει ανοιχτό license.

Σε κάθε περίπτωση σκέφτομαι να ξεκινήσω ένα open source project σε gosu για να φτιάξουμε ένα μικρό 2D παιχνιδάκι, οπότε όποιος/α θέλει να συμμετάσχει θα μπορέσει να δει κώδικα εκεί :smile:. Θα στείλω μια ανακοίνωση εδώ, οπότε είναι καλή ιδέα να κάνετε watch αυτό το repository αν δεν το έχετε κάνει ήδη.

#### Rubyzino 39

##### Swap two values:

```ruby
x, y = y, x
```

---

##### Inner assignment

```ruby
if vals.any?
  retval = do_something(vals)
else
  retval = do_something_different
end
```

---

##### Inner assignment after

```ruby
retval = if vals.any?
           do_something(vals)
         else
           do_something_different
         end
```

---

##### Return

```ruby
def something
  b = 1
  c = 2
  a = b + c
  return a
end
```

---

##### Return after

```ruby
def something
  b = 1
  c = 2
  a = b + c
end
```

**Comment by nelaka** [comment]
Αχ τι ωραία! :+1:

**Comment by xpy** [comment]
Με τον κίνδυνο να φανώ σπασικλάκι...
Το `x, y = y, x` γίνεται και στην Python.
Το αναφέρω απλά επειδή ρωτήθηκε.

**Comment by petros** [comment]
Όχι, καθόλου σπασικλάκι. Ίσα ίσα, καλό είναι να ξέρουμε και ποιες άλλες γλώσσες το υποστηρίζουν. Thanks @xpy! :smile:

**Comment by Drakevr** [comment]
@petros yup, ανέβασε τη :)
καλο θα είναι να ανεβάσουνε και τα κορίτσια τη δικη τους.
Ενα φάκελο ( 39/ ) και όλα τα resources του meetup εκεί;  (rubyzino.txt(?) included)
Οπως γινότανε στα πρώτα meetups.

CC @SolarBlue / @aefstratia

**Comment by sortingbubbles** [comment]
Τη παρουσίαση μπορείτε να τη βρείτε [εδώ](https://docs.google.com/presentation/d/1OjRjgzPGPb15jwtUBpItsRVTUvmoojRdY9YQ4QgPoj8/edit?usp=sharing).
