### ISSUE TITLE
Backend Developer needed

### ISSUE THREAD

**Issue by andreas-trad** [thessrb/meetup#88]
Η εταιρεία kissmybutton.gr αναζητά Senior Backend Developer για να στελεχώσει το backend development team.

Η KissMyButton ιδρύθηκε το 2004 και είναι software house με βάση τη Θεσσαλονίκη το οποίο αναλαμβάνει την ανάπτυξη, εξέλιξη και υποστήριξη custom web applications. Η εταιρεία μας έχει μόνιμες συνεργασίες με σειρά σημαντικών (σε παγκόσμιο επίπεδο) πελατών και εξειδικεύεται στην ανάπτυξη intuitive, μοντέρνων, εύκολων στη χρήση web applications απευθυνόμενων σε business & end users.

Ο άνθρωπος που αναζητούμε:
- θα ενσωματωθεί στην δύναμη του development team ως backend developer
- θα συμμετάσχει σε σειρά επιλεγμένων projects, ποικίλου μεγέθους και complexity
- θα συμμετάσχει ενεργά σε meetings με τους πελάτες και στη λήψη τεχνικών και χρονικών αποφάσεων

Τα απαραίτητα χαρακτηριστικά που αναζητούμε είναι:
- βαθυά γνώση / εμπειρία σε επίπεδο backend web development (ενδεικτικά: REST APIs, oAuth2)
- ευκολία στην εκμάθηση νέων τεχνολογιών
- αναλυτικό μυαλό / ευχέρεια στην κατανόηση και την ανάλυση των προδιαγραφών
- self motivated
- team player
- παθιασμένος για την τεχνολογία

Σε τεχνικό επίπεδο αναζητούμε τα ακόλουθα (σε παρένθεση αναφέρεται η σημαντικότητα κάθε τεχνολογίας σε εύρος από 0 έως 100):
- Ruby on Rails (85/100)
- Node.js (70/100)
- Relational dbs (80/100)
- NoSQL dbs (70/100)
- Git (90/100)
- AWS (70/100)
- Ability to setup and automate deployment processes (60/100)
- Any frontend experience is welcome (50/100) 

Η θέση αφορά πλήρη απασχόληση κατά ισχυρή προτίμηση εντός των γραφείων της εταιρείας (Θεσσαλονίκη).

Για οποιαδήποτε πληροφορία ή για αιτήσεις παρακαλώ αποστείλατε το βιογραφικό σας (ή linkedin profile) στο email: [andreas@e-labs.gr](mailto:andreas@e-labs.gr).

Επίσης στη διάθεση των υποψηφίων τίθενται τα τηλέφωνα:
- 2313016444
- 6948820175

Υπεύθυνος: Ανδρέας Τραντίδης

**Comment by vasspilka** [comment]
Is this only on-site, are you considering remote aswell?
